name: Environment Variables

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: I_AM_WORKFLOW_SCOPED

jobs:
  job-1:
    runs-on: ubuntu-slim
    env:
      JOB_VAR: I_AM_JOB_SCOPED
    steps:
      - name: Inspect scopes job 1 step 1
        env:
          STEP_VAR: I_AM_STEP_SCOPED
        run: |
          echo "WORKFLOW_VAR : $WORKFLOW_VAR"
          echo "JOB_VAR : $JOB_VAR"
          echo "STEP_VAR : $STEP_VAR"
      - name: Inspect scops job 1 step 2
        run: |
          echo "WORKFLOW_VAR : $WORKFLOW_VAR"
          echo "JOB_VAR : $JOB_VAR"
          echo "STEP_VAR : $STEP_VAR"
  job-2:
    runs-on: ubuntu-slim
    steps:
      - name: Inspect scop job 2 step 1
        run: |
          echo "WORKFLOW_VAR : $WORKFLOW_VAR"
          echo "JOB_VAR : $JOB_VAR"
          echo "STEP_VAR : $STEP_VAR"
