name: Triggering Events

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - "feature/*"
  
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    paths:
      - "src/**/*"

  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  echo-event:
    runs-on: ubuntu-slim
    steps:
      - name: Step name
        run: |
          echo "Ajay you are doing good job"