name: Triggering Events

on:
  workflow_dispatch:

  push:
    branches:
      - "feature/*"
    paths:
      - "core-features/filter/*.md"
      - "!core-features/filter/*.txt"
  
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
    paths:
      - "core-features/filter/*.md"
      - "!core-features/filter/*.txt"

  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  echo-event:
    runs-on: ubuntu-slim
    steps:
      - name: Step name
        run: |
          echo "Ajay you are doing good job"